Check lib size in CI

diff --git a/ci/cloudbuild/vizzu-devenv-prebuild-docker.yaml b/ci/cloudbuild/vizzu-devenv-prebuild-docker.yaml
--- a/ci/cloudbuild/vizzu-devenv-prebuild-docker.yaml
+++ b/ci/cloudbuild/vizzu-devenv-prebuild-docker.yaml
@@ -56,6 +56,33 @@ steps:
     waitFor:
       - wasm_cmake
     timeout: 1800s
+  - name: gcr.io/cloud-builders/gsutil
+    args:
+      - cp
+      - 'gs://vizzu-lib-main/lib-size/size.txt'
+      - '/workspace/build/cmake-wasm/weblib/size_downloaded.txt'
+    id: download_size
+    waitFor:
+      - wasm_make
+  - name: vizzu/vizzu-devenv:v0.8.x
+    args:
+      - bash
+      - '-c'
+      - |
+        threshold=1.05
+        while IFS= read -r line; do
+          file=$(echo "$line" | cut -d ' ' -f 1)
+          actual_size=$(echo "$line" | cut -d ' ' -f 2)
+          downloaded_size=$(grep "$file" /workspace/build/cmake-wasm/weblib/size_downloaded.txt | cut -d ' ' -f 2)
+          if [[ -n "$downloaded_size" && $(echo "$actual_size > $downloaded_size * $threshold" | bc -l) -eq 1 ]]; then
+            echo "Error: File $file size exceeds the threshold."
+            exit 1
+          fi
+        done < /workspace/build/cmake-wasm/weblib/size.txt
+    id: check_size
+    dir: /workspace/build/cmake-wasm
+    waitFor:
+      - download_size
   - name: vizzu/vizzu-devenv:v0.8.x
     args:
       - node
@@ -106,6 +133,7 @@ steps:
       - .
     id: test_integration
     waitFor:
+      - check_size
       - test_jsUnit
       - test_desktopUnit
       - test_wasmUnit
@@ -141,6 +169,7 @@ steps:
         if [ $BRANCH_NAME == "main" ]
         then
           gsutil -m cp -r '/workspace/example/lib/*' 'gs://vizzu-lib-main/lib'
+          gsutil -m cp '/workspace/build/cmake-wasm/weblib/size.txt' 'gs://vizzu-lib-main/lib-size/size.txt'
         fi
     id: lib_upload
     waitFor:
